---
abstract: 'a source filter for inline code templates (macros)'
author:
  - 'Rocco Caputo <rcaputo@cpan.org>'
build_requires:
  Scalar::Util: 1.29
  Test::More: 0.98
  lib: 0
  perl: 5.004
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Filter-Template
requires:
  Carp: 1.26
  Filter::Util::Call: 1.49
  Symbol: 1.06
  bytes: 0
  constant: 0
  strict: 0
  vars: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Filter-Template
  homepage: http://search.cpan.org/dist/Filter-Template/
  license: http://dev.perl.org/licenses/
  repository: git://github.com/rcaputo/filter-template.git
version: 1.043
