--- #YAML:1.0
name:                Filter-Template
version:             1.02
abstract:            Source filter for inline code templating.
license:             unknown
generated_by:        ExtUtils::MakeMaker version 6.30_01
author:              Rocco Caputo <rcaputo@cpan.org>
distribution_type:   module
requires:     
    Filter::Util::Call:            1.06
    Test::More:                    0
meta-spec:
    url: <http://module-build.sourceforge.net/META-spec-new.html>;
    version: 1.1
